# Generated by Django 4.2.7 on 2026-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='core.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
