# Generated by Django 4.2.7 on 2026-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_doctor_hospital_doctor_hospitals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Bhojpur', 'Bhojpur'), ('Dhankuta', 'Dhankuta'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Khotang', 'Khotang'), ('Morang', 'Morang'), ('Okhaldhunga', 'Okhaldhunga'), ('Panchthar', 'Panchthar'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Solukhumbu', 'Solukhumbu'), ('Sunsari', 'Sunsari'), ('Taplejung', 'Taplejung'), ('Terhathum', 'Terhathum'), ('Udayapur', 'Udayapur'), ('Saptari', 'Saptari'), ('Siraha', 'Siraha'), ('Dhanusha', 'Dhanusha'), ('Mahottari', 'Mahottari'), ('Sarlahi', 'Sarlahi'), ('Rautahat', 'Rautahat'), ('Bara', 'Bara'), ('Parsa', 'Parsa'), ('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Chitwan', 'Chitwan'), ('Nuwakot', 'Nuwakot'), ('Dhading', 'Dhading'), ('Rasuwa', 'Rasuwa'), ('Sindhupalchok', 'Sindhupalchok'), ('Makwanpur', 'Makwanpur'), ('Ramechhap', 'Ramechhap'), ('Dolakha', 'Dolakha'), ('Sindhuli', 'Sindhuli'), ('Khotang', 'Khotang'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahu', 'Tanahu'), ('Syangja', 'Syangja'), ('Kaski', 'Kaski'), ('Manang', 'Manang'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Baglung', 'Baglung'), ('Arghakhanchi', 'Arghakhanchi'), ('Gulmi', 'Gulmi'), ('Kapilvastu', 'Kapilvastu'), ('Nawalpur', 'Nawalpur'), ('Palpa', 'Palpa'), ('Rupandehi', 'Rupandehi'), ('Dang', 'Dang'), ('Bardiya', 'Bardiya'), ('Banke', 'Banke'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum East', 'Rukum East'), ('Rukum West', 'Rukum West'), ('Salyan', 'Salyan'), ('Dailekh', 'Dailekh'), ('Jajarkot', 'Jajarkot'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Mugu', 'Mugu'), ('Humla', 'Humla'), ('Dolpa', 'Dolpa'), ('Baitadi', 'Baitadi'), ('Darchula', 'Darchula'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Achham', 'Achham'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur'), ('Dadeldhura', 'Dadeldhura')], max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('Province 1', 'Province 1'), ('Province 2', 'Province 2'), ('Bagmati Province', 'Bagmati Province'), ('Gandaki Province', 'Gandaki Province'), ('Lumbini Province', 'Lumbini Province'), ('Karnali Province', 'Karnali Province'), ('Sudurpashchim Province', 'Sudurpashchim Province')], max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Bhojpur', 'Bhojpur'), ('Dhankuta', 'Dhankuta'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Khotang', 'Khotang'), ('Morang', 'Morang'), ('Okhaldhunga', 'Okhaldhunga'), ('Panchthar', 'Panchthar'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Solukhumbu', 'Solukhumbu'), ('Sunsari', 'Sunsari'), ('Taplejung', 'Taplejung'), ('Terhathum', 'Terhathum'), ('Udayapur', 'Udayapur'), ('Saptari', 'Saptari'), ('Siraha', 'Siraha'), ('Dhanusha', 'Dhanusha'), ('Mahottari', 'Mahottari'), ('Sarlahi', 'Sarlahi'), ('Rautahat', 'Rautahat'), ('Bara', 'Bara'), ('Parsa', 'Parsa'), ('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Chitwan', 'Chitwan'), ('Nuwakot', 'Nuwakot'), ('Dhading', 'Dhading'), ('Rasuwa', 'Rasuwa'), ('Sindhupalchok', 'Sindhupalchok'), ('Makwanpur', 'Makwanpur'), ('Ramechhap', 'Ramechhap'), ('Dolakha', 'Dolakha'), ('Sindhuli', 'Sindhuli'), ('Khotang', 'Khotang'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahu', 'Tanahu'), ('Syangja', 'Syangja'), ('Kaski', 'Kaski'), ('Manang', 'Manang'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Baglung', 'Baglung'), ('Arghakhanchi', 'Arghakhanchi'), ('Gulmi', 'Gulmi'), ('Kapilvastu', 'Kapilvastu'), ('Nawalpur', 'Nawalpur'), ('Palpa', 'Palpa'), ('Rupandehi', 'Rupandehi'), ('Dang', 'Dang'), ('Bardiya', 'Bardiya'), ('Banke', 'Banke'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum East', 'Rukum East'), ('Rukum West', 'Rukum West'), ('Salyan', 'Salyan'), ('Dailekh', 'Dailekh'), ('Jajarkot', 'Jajarkot'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Mugu', 'Mugu'), ('Humla', 'Humla'), ('Dolpa', 'Dolpa'), ('Baitadi', 'Baitadi'), ('Darchula', 'Darchula'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Achham', 'Achham'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur'), ('Dadeldhura', 'Dadeldhura')], max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('Province 1', 'Province 1'), ('Province 2', 'Province 2'), ('Bagmati Province', 'Bagmati Province'), ('Gandaki Province', 'Gandaki Province'), ('Lumbini Province', 'Lumbini Province'), ('Karnali Province', 'Karnali Province'), ('Sudurpashchim Province', 'Sudurpashchim Province')], max_length=50),
        ),
    ]
